### PR TITLE
Compatibility with new 3D player thingy

### PR DESCRIPTION
**Pull request by sdzen**
sorry about there being no backward compatibility but I didn't see a need for it.

### CODE REVIEW

**Comment by PilzAdam** [comment]
I wait until 0.4.4 stable gets released.

**Comment by sdzen** [comment]
okay then could you just put a link to my github page and have it there on your forum topic for people running the 0.4.4 dev? just a request you don't need to fullfill if you dont want toBest wishes
Abel Kurt Millay
thank you for using the sdzen email service
Get your own email service at ZZN.COM.

**Comment by PilzAdam** [comment]
I already did that.

**Comment by PilzAdam** [comment]
Now master supports 3d models.

**Pull request closed without merging**
